apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: account-management
  description: The uidam accounts API
  tags:
    - uidam
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: ignite-core-grouop
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Swagger Account Management
      license:
        name: MIT
    servers:
      - url: http://uidam.swagger.io/v1
    paths:
      /accounts/:
        get:
          summary: List all accounts
          operationId: listAccounts
          tags:
            - accounts
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: A paged array of accounts
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Account"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a account
          operationId: createAccounts
          tags:
            - accounts
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /accounts/{accountId}:
        get:
          summary: Info for a specific account
          operationId: showByAccountId
          tags:
            - accounts
          parameters:
            - name: accountId
              in: path
              required: true
              description: The id of the account to retrieve
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Account"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Account:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        Accounts:
          type: array
          items:
            $ref: "#/components/schemas/Account"
        Error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
